name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-build --configuration Release --verbosity minimal --logger "trx;LogFileName=test_results.trx"

      - name: Upload test results (trx)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: '**/TestResults/*.trx'

      - name: Publish TRX results to GitHub Checks (annotations)
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: dotnet-tests
          path: '**/TestResults/*.trx'
          reporter: dotnet-trx

      - name: Annotate failed tests
        if: failure()
        run: echo "One or more tests failed. See artifacts 'test-results' for TRX files."
